name: live
main: eu.falcraft.LivePlugin
version: 2
api-version: 1.13

commands:
  live:
    description: When streaming, can also be used to get the link of a streaming channel
  aa:
    description: one-line ascii art on demand